### ISSUE TITLE
Networking the Game

### ISSUE THREAD

**Issue by bwwagner** [bwwagner/ALytlePokerGame#3]
The game needs a client(players) and a server(dealer).

We should probably use Java socket for TCP communication between the client and server. I have been reading sites at [tutorialspoint](http://www.tutorialspoint.com/java/java_networking.htm) and [Ray Toal's Java Socket Examples](http://cs.lmu.edu/~ray/notes/javanetexamples/).  They seem to be pretty straightforward to set up, but we'll have to tweak the game logic.

We can listen for new players either at the start of a hand, or we can listen only at the start of a new pot.  If we have time this could be separate game modes.  Another thing to consider is if we want the server to be able to play the game.  I think it is better to just have a dedicated server and can't play the game.

**Comment by bwwagner** [comment]
I checked with Dr. Doyle, and he said we could use Java Socket to implement our client and server.

**Comment by jrlytle** [comment]
Hey Brandon, I just added my current version of the PokerServer, called PokerServer.java. I left this comment in the commit and I'm posting it here also as documentation and easier access: (I still need to add in the ability for a player to get their hand. I'm not sure how to do this)

Added my version of the Poker Server using LPokerServer as a starting template and Tic Tac Toe Server from a website as a reference. I know that the methods involving adding cards to the deck, drawing hands for two players, and getting card images for drawn cards work, but I'm not sure if the connection to the clients will work. The only thing the client need to do is grab the images from handOneCards and handTwoCards, go through tradeCards method, then run faceOff Method to get the winner. I'm not sure how to handle the ante phase. I'm going to keep messing with the code and try to do some checks with it. Let me know if anything is wrong with the code or if something isn't working on your end.

**Comment by bwwagner** [comment]
Is the server supposed to have a graphical interface?  Because I don't see it passing any connection messages or starting the game.

Also, I thought we were creating separate classes for things like showing the hands and betting.

**Comment by bwwagner** [comment]
The examples show passing Strings back and forth (some have the socket connections on a separate class).  Since we are doing TCP this is probably good enough for us.

I'm thinking of passing the 2D hand array to the client something like this
**In pseudocode:**
```
String hand = "2H JD KH AS 0C"  // 0 = 10, Letters are Suits
Server.send(hand)
Client.listen() = handOne    //handOne is player's hand handTwo is opponent's hand
h1[0] = getCard(handOne.split("\s"))
```

Probably best to keep it to two players for now.

**Comment by jrlytle** [comment]
The client is supposed to create it's own graphics interface, bring in the array of cards chosen by the server and then translate that into the images and then add those images to the interface. I thought it might be a little simpler to have all of the methods in the server class because then you can just call on them when you need them rather than creating class objects and calling on the classes that way. If you think it would be cleaner and clearer, then I can change it.

Yea, I think we should keep it two players for now too. I've been messing around with the server some more (and a client too) just to see what I can get away with before it messes up. I'm trying my best to not take away coding from you, but it's difficult to make a server without knowing how the client is set up and vice versa. That's why the server I created is not finished yet. I'm still working on it right now and the rest of the weekend I will be able to spend on it since I finally solved the bug on the Rubik's Cube for Interactive Graphics.

**Comment by jrlytle** [comment]
Oh wow, is the client finished? It looks really good if it is. Did you want me to do some testing using it?

**Comment by bwwagner** [comment]
The client is close, but I need to figure out how you want to send and receive the game stage changes.  The two main reasons I wanted to have a separated class for the methods is for separation of concerns and to keep from duplicating code.  However that really isn't important as long as it works.

If you need to change something on the client go ahead.  I already changed some minor things on the server side.

**Comment by jrlytle** [comment]
I think it looks fine. I'm just not sure what I need to do to the server to get it to pass an array to the clients. I think that's the only part left on that side. Otherwise, it's just a matter of calling the methods at the right time. I'm going to download the client to see if I can get it to communicate with my server.

**Comment by jrlytle** [comment]
Hey, I just tried downloading and running it, and nothing is working now. I had everything displaying on the client, and now nothing displays. Could you please help me get it back up and running?

**Comment by jrlytle** [comment]
I just worked with it and got it to the point that it runs and displays cards, only I had to comment out all the betting portions. For some reason it crashes if those are left in. I'm back to working on hiding the opponents cards. It'll be close on whether or not I can get it finished before class, but if I can get it a bit closer, we'll for sure have the network portion done, which will give us a decent presentation.

**Comment by jrlytle** [comment]
I just successfuly got two clients to open and they have different hands. Now to make sure that they can get the opposite player's hand. I'm a little more hopeful that it will be presentable.

**Comment by bwwagner** [comment]
When will you be able to push your code?

**Comment by jrlytle** [comment]
I can push what I have now, but I still haven't figured out the last issue of geting the player the opponent's cards.

**Comment by jrlytle** [comment]
I just pushed what I've done. Like I said, we can prove that we've got a Server/Client communication going on, but the game isn't done.

**Comment by jrlytle** [comment]
Oh, and the betting part is commented because it wouldn't work on my computer otherwise.

**Comment by jrlytle** [comment]
Just an update: I was able to get each client to get the opponent's hand and display that on their screen at the top. The client displays their own hand at the bottom. All the data matches on both screens and the clients are pulling from the same deck. Unfortunately, I'm using the same code that I have been since yesterday. How difficult was it to add in the betting portion?

**Comment by bwwagner** [comment]
Just uncomment the lines.  

If you want to get rid of the warning, that will take a bit more work.  I am not sure if it's worth the effort though.

**Comment by jrlytle** [comment]
Another update: I've taken a sledgehammer approach to get it as close to finished as possible - I've added in the code where the hands are compared and the winner is declared. Games are as short as the the window being brought up and the game is done. I'm still working on the trading cards part, but another bug has appeared that has taken priotiy - When the hands are drawn, duplicates tend to appear in opposite hands, sometimes in the same player's hand. I think it has something to do with each player having its own thread and they tend to run each other over to get cards for their hand. I'm not sure how to solve it yet, but it will get as much of my attention today as I can give it. If all else fails though, it's a Distributed Systems problem instead of a Network problem, so it shouldn't be too big of a deal.
